"""
embed_texture.py
Embeds world.jpg as a base64 data URL into a companion world-texture.js file,
then patches weather-os.html to load it. Run this once to enable satellite
texture when opening the HTML directly as a local file (file:// protocol).
"""
import base64, re

fui = r'C:\Users\arago\Documents\Claude\Projects\FUI'
jpg_path  = fui + r'\world.jpg'
html_path = fui + r'\weather-os.html'
js_path   = fui + r'\world-texture.js'
done_path = fui + r'\embed_done.txt'

try:
    # 1. Read world.jpg and encode as base64 data URL
    with open(jpg_path, 'rb') as f:
        jpg_bytes = f.read()
    data_url = 'data:image/jpeg;base64,' + base64.b64encode(jpg_bytes).decode()

    # 2. Write world-texture.js
    with open(js_path, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by embed_texture.py — do not edit manually\n')
        f.write("window.WORLD_JPG_DATA_URL='" + data_url + "';\n")

    # 3. Patch weather-os.html
    with open(html_path, 'r', encoding='utf-8') as f:
        html = f.read()

    # Add script tag for world-texture.js right after <head>
    script_tag = '<script src="./world-texture.js"></script>'
    if script_tag not in html:
        html = html.replace('<head>', '<head>\n' + script_tag, 1)

    # Replace the img.src line to use the data URL variable
    old_src = "img.src='./world.jpg';"
    new_src = "img.src=window.WORLD_JPG_DATA_URL||'./world.jpg';"
    if old_src in html:
        html = html.replace(old_src, new_src, 1)

    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(html)

    with open(done_path, 'w') as f:
        f.write('SUCCESS\njpg_bytes=%d\ndata_url_len=%d\n' % (len(jpg_bytes), len(data_url)))
    print('Done! world-texture.js written and weather-os.html patched.')

except Exception as e:
    with open(done_path, 'w') as f:
        f.write('ERROR: ' + str(e) + '\n')
    print('Error:', e)
